server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/users/ {
        proxy_pass http://user-service:8001/;
    }

    location /api/restaurants/ {
        proxy_pass http://restaurant-service:8002/;
    }

    location /api/owner/ {
        proxy_pass http://restaurant-owner-service:8003/;
    }

    location /api/reviews/ {
        proxy_pass http://review-service:8004/;
    }
}
