apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-worker
  labels:
    app: review-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-worker
  template:
    metadata:
      labels:
        app: review-worker
    spec:
      nodeSelector:
        karpenter.sh/nodepool: general-purpose
      containers:
        - name: review-worker
          image: 463310123657.dkr.ecr.us-east-2.amazonaws.com/review-worker:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
