apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app: app-secrets
type: Opaque
data:
  JWT_SECRET_KEY: c3VwZXItc2VjcmV0LWNoYW5nZS1tZQ==
  TAVILY_API_KEY: ""
  GEMINI_API_KEY: ""
  HF_API_TOKEN: ""
